### ISSUE TITLE
Two issues with the docs

### ISSUE THREAD

**Issue by cheerfulstoic** [Nexosis/nexosisclient-rb#14]
The docs have you bring the gem into the `Gemfile` like so:

```ruby
gem 'nexosis_api', '>= 2.0.0'
```

Not a big deal, but `'~> 2.0` or `'~> 2.2.0'` is generally better form because it doesn't allow you to update to 3.0 (or 2.3.0 in the latter case, depending on how closely you follow semantic versioning) unless you specifically say that's what you want.  With `'>= 2.0.0'` if the users ever do a `bundle update` they'll end up with a version of `nexosis_api` which may be incompatible with their app.

More importantly, though, when I run the last line in the docs (`balance = NexosisApi.client.get_account_balance`) I get:

```ruby
NoMethodError: undefined method `get_account_balance' for #<NexosisApi::Client:0x007fa4a18b3ab0>
Did you mean?  get_account_quotas
from (pry):6:in `<main>'
```

**Comment by cheerfulstoic** [comment]
I also just noticed in the "Datasets: Add data" section of your docs that you're using `Net::HTTP` instead of the client gem, so I think I'm just going to need to poke around at what methods are available in the `README` either...

**Comment by bhinks** [comment]
@cheerfulstoic Thanks for the feedback! The issues you pointed out with the documentation will be addressed shortly. 

> ...in the "Datasets: Add data" section of your docs that you're using Net::HTTP instead of the client gem...

The API reference documentation is prepared as new features are added to the API, which tends to stay a few steps ahead of our client libraries. So the examples presented there won't include references to the client library functionality, but rather tools that can be used with (often) a base installation of the language.

**Comment by bhinks** [comment]
The documentation has been updated at: https://docs.nexosis.com/clients/ruby

Thanks again for the feedback!

**Comment by cheerfulstoic** [comment]
Thanks!
